sudo: required

services:
  - docker

before_install:
  - docker build -t lesinko/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lesinko/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: #created with elasticbeanstalk
  bucket_name: #enter the name of the bucket created by ELK
  bucket_path: #same as app
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY